### ISSUE TITLE
TypeScript error on first clone

### ISSUE THREAD

**Issue by completer** [sst/monorepo-template#1]
Follow steps in `readme.md`.

There is a TypeScript error in `packages/scripts/tsconfig.json`

    Option 'bundler' can only be used when 'module' is set to 'preserve' or to 'es2015' or later.

(There is also type error in packages/scripts/src/example.ts which isn't resolved until the `npx sst deploy` step.)

**Comment by steduardo** [comment]
Without really knowing if it will have bad side effects, I followed the advice here https://stackoverflow.com/a/78087127/523934 and set 

```
"module": "NodeNext"
"moduleResolution": "NodeNext"
```

Appreciate someone verifying if I'm an idiot or not :)

**Comment by jayair** [comment]
Hmm I don't remember seeing this but I'll test it out.

**Comment by jayair** [comment]
I'm not getting this. This is after I run `npm install`. Both in VS Code and Neovim.

<img width="498" alt="Screenshot 2024-09-03 at 5 05 52 PM" src="https://github.com/user-attachments/assets/d7024d63-4747-43ad-85ee-42034e8a0a8e">

<img width="420" alt="Screenshot 2024-09-03 at 5 06 13 PM" src="https://github.com/user-attachments/assets/54ea401d-602e-42cb-8e90-b17656ab1a1b">

Are you running a different version of TS in your language server for your IDE?

**Comment by steduardo** [comment]
Quick update; I'm running this in a GitHub Codespace. 

Originally I got the TS error with NodeNext/Bundler & changing compilerOptions to NodeNext/NodeNext resolved it.

So I just switched back to:

`"module": "NodeNext"
"moduleResolution": "Bundler"`

And I no longer see the TS error. Checked the current TS language server version in the Codespace build: 5.5.4. 

I guess GitHub rolled out a new VS Code build for the Codespace which has a more up to date setup; don't think there's a way to see what it was before though.

Thanks for looking into it. 

Big thanks to you & the team for your amazing work on SST! You've built something special here.

**Comment by msbeeman** [comment]
FYI I'm getting this error as well after a fresh npm install

**Comment by msbeeman** [comment]
Hey guys, I'm running this in VS code on the most up to date version and am having the same issues after a fresh npm install 
<img width="1745" alt="image" src="https://github.com/user-attachments/assets/80ba8f31-10af-462a-902e-9c5faada1c0d">

**Comment by tropicbliss** [comment]
Also facing this error on my local install of VSCode: TS version 5.5.4

**Comment by jayair** [comment]
Hmm how do I reproduce this. Could any VS Code plugins be interfering?

**Comment by tropicbliss** [comment]
It can be reproduced with no plugins installed. Though I don't think we are using bun and just plain npm, so maybe you can try disabling that
