### ISSUE TITLE
Rename Script

### ISSUE THREAD

**Issue by Shipalan** [sst/monorepo-template#10]
I might just be using it wrong, but the guide tells me to use "npx replace-in-file /monorepo-template/g notes **/*.* --verbose"
When I do, after changing the name I want. It just tells me "No files were changed"

**Comment by jayair** [comment]
I don't remember what it had previously said. But did it rename the files for you?

**Comment by ttarabbia** [comment]
Having the same issue on OSX. 
Single quotes around the arguments worked for me. 
`npx replace-in-file '/monorepo-template/g' 'notes' '**/*.*' --verbose`

**Comment by jayair** [comment]
I guess we can close this now
