### ISSUE TITLE
sst cli not working on Windows

### ISSUE THREAD

**Issue by TomasHovorka** [sst/monorepo-template#3]
Hi,

I am getting this when cloned the repo, run `npm install` and try to dev:
```
>npx sst dev   
It seems that your package manager failed to install the right version of the SST CLI for your platform. You can try manually installing the "sst-win32-x64" package.
```

I am new to SST, sorry if its something obvious. I am trying to follow the sst guide. I am on Win 10 pc. Is the ion version of sst not supposed to work on windows? 
Thanks

**Comment by jayair** [comment]
Ah yeah we don't have Windows support yet. It's WSL only at the moment.

You can track this here https://github.com/sst/ion/issues/347
